# Generated by Django 4.2.16 on 2024-11-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_id', models.CharField(max_length=100, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('power', models.FloatField()),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
